# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-usb-boot"
BBFILE_PATTERN_meta-usb-boot = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-usb-boot = "6"

LAYERDEPENDS_meta-usb-boot = "core"
LAYERSERIES_COMPAT_meta-usb-boot = "kirkstone"
