LABEL primary
    MENU LABEL primary kernel
    LINUX /boot/Image
    INITRD /boot/initrd
    FDT /boot/tegra210-p3448-0000-p3449-0000-b00.dtb
    APPEND ${cbootargs} root=/dev/sda1 rootwait rw usbcore.autosuspend=-1
