# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-confluxr"
BBFILE_PATTERN_meta-confluxr = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-confluxr = "6"

LAYERDEPENDS_meta-confluxr = "core"
LAYERSERIES_COMPAT_meta-confluxr = "kirkstone"
